### ISSUE TITLE
Cant get postfix and dovecot to use the same maildir

### ISSUE THREAD

**Issue by johnsonbrothers** [thkukuk/containers-mailserver#1]
Hi, thanks for making this public. I found this via openSUSE and podman containers.

I have a setup for my self with openldap, postfix and dovecot on a MicroOS-server.

But, i have a problem to get postfix and dovecot to use the same Maildir.
When i start postfix, all mail is delivered to /var/opt/postfix/vmail/<domain name>/<username>/new
Dovecot try to find mail at /var/opt/postfix/vmail/<username>/Maildir/new
(/var/opt/postfix/vmail is my data persistent directory for /var/spool/vmail)

And i cant find a parameter in either container to configure this in /etc/default/container postfix, /etc/default/container-dovecot or in my openldap-entry for the user.

Do you have some tips to solve this?

**Comment by thkukuk** [comment]
I have no idea if sharing the directories between postfix and dovecot is possible at all. Most articles I found about this (like https://workaround.org/ispmail/jessie/postfix-dovecot) write that you either have to use dovecot-lda or lmtp. Since dovecot-lda and postfix are in two different containers, this option does not exist. That's why I use since years lmtp to deliver local mails from postfix to dovecot.
Could be that there were changes in the last years, since my setup with lmtp works fine for me, there was no need for me to look for other/new alternatives.

And yes, I should provide much more documentation and examples about this, if I would just find the time to do it...

**Comment by johnsonbrothers** [comment]
Thanks, I'll look in to that. Maybe you have some configuration that could help me? (Maybe link https://workaround.org/ispmail/jessie/postfix-dovecot enough?)

Thank you for your quick answer.

**Comment by thkukuk** [comment]
For postfix I use:

```
DEBUG=0
TZ=Europe/Berlin
VIRTUAL_MBOX=1
USE_LDAP=1
LDAP_USE_TLS=1
LDAP_BASE_DN="dc=example,dc=org"
SERVER_HOSTNAME="mail.example.org"
VIRTUAL_DOMAINS="example.org"
MASQUERADE_DOMAINS="example.org"
LDAP_SERVER_URL="ldap://ldap.example.org"
LMTP="example.org"
...
```

**Comment by johnsonbrothers** [comment]
Wow, so easy. It worked straight away.
Thanks.

I have taken some notes along the way. Are you interested in them, to use them as an example?
